export const HHU_LOCATIONS="HHU_LOCATIONS";
export const CUSTOMER_LOCATIONS="CUSTOMER_LOCATIONS";
export const DRAWING="DRAWING";
export const ILLEGAL_CONNECTIONS="ILLEGAL_CONNECTIONS";
export const COMPLAINTS="COMPLAINTS";
export const SETTINGS="SETTINGS";